# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Password123!
  host: localhost

development:
  <<: *default
  database: event_management_dev

test:
  <<: *default
  database: event_management_test

production:
  <<: *default
  database: event_management_prod
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
